### PR TITLE
feat: finished the survey detail page, privacy policy, tnc

### PR DESCRIPTION
**Pull request by artikandri**
### What's new
- ui/src/views/user/survey-detail/components/* : components for survey detail page
- ui/src/plugins/vuetify-friendly-iframe.js: a new plugin to load iframe from dynamic url

### What's changed
- ui/package.json: added a new package to help loading iframe from dynamic url 
- ui/src/assets/json/survey-data-sample.json: updated the json sample file
- ui/src/components/BottomSheet.vue: refactored a bit; emitted an event called 'close' when clicking the close button
- ui/src/components/ContentCard.vue: modified the styling a bit; including the !important property in the mixins
- ui/src/form-builder/components/GenerateForm.vue: added props to disable form item and to show/hide submit button
- ui/src/form-builder/components/GenerateFormItem.vue: added new prop to disable form item
- ui/src/views/user/survey-edit/components/SurveySettings.vue: added new prop to show/hide date editing
- ui/src/views/user/signup-thankyou/SignupThankyouView.vue: tidied a bit
- ui/src/plugins/index.js: imported a new plugin, vuetify-friendly-iframe
- ui/src/styles/mixins/_typography.scss: added a new property to the font-size mixin; now we can set the importance of the newly set font-size
- ui/src/util/dates.js: added several date helpers
- ui/src/styles/variables.js: added a new color, "lightBlue"
- ui/src/views/general/privacy-policy/PrivacyPolicyView.vue: finished the privacy policy view 
- ui/src/views/general/terms-and-conditions/TermsAndConditionsView.vue: finished the terms and conditions view

### Notable
- the mobile design ended up a bit different (the tabs color is different) because I think the default one is good enough XD
- Instead of coding from scratch, now the summary will be loaded directly from url given by BE. Right now the summaryUrl is still using the localhost:8080/ link, which should be localhost:8000, yet cannot test it because I still got problems with docker
- added a new property in the @font-size mixin to set the font size property (defaults to nothing). This is especially useful if we need to override the default font-size set by vuetify

### To do
- API implementation, axios setting
- validation on survey builder page

#### Desktop
imageimage
image
image
image
image
image
image
image

After datatable removal: 
image

#### Mobile
image
image
image
image
image
image
image

### CODE REVIEW

**Review by teddy-f-47 — APPROVED** [review]
Thank you very much for your hard work! I think everything is ok. I'm not sure if you will add more changes after your discussion with the back-end regarding embedding iframes for survey summary but I see here that the dependency for embedding iframes has been added already. So, this is approved for merging, but if you need to add more changes you are free to do so. Once again, thank you for the great work.

**Comment by artikandri** [comment]
> Thank you very much for your hard work! I think everything is ok. I'm not sure if you will add more changes after your discussion with the back-end regarding embedding iframes for survey summary but I see here that the dependency for embedding iframes has been added already. So, this is approved for merging, but if you need to add more changes you are free to do so. Once again, thank you for the great work.

I have revised the code after the discussion; I removed the whole datatable  in the responses tab, replaced the survey.data.link with a generated link from FE, and handled the condition when a user accessed a survey that has not yet to be published.

**Comment by artikandri** [comment]
> Thank you very much for your hard work! I think everything is ok. I'm not sure if you will add more changes after your discussion with the back-end regarding embedding iframes for survey summary but I see here that the dependency for embedding iframes has been added already. So, this is approved for merging, but if you need to add more changes you are free to do so. Once again, thank you for the great work.

The dependency was already added because I knew that the summary page will be generated by BE; however I didnt remember that the responses will also be handled by BE; so I still worked on it. XD

**Review by teddy-f-47 — APPROVED** [review]
Thank you, everything seems to be ok. Approved for merging.

**Pull request merged**
