### PR TITLE
Finished connecting APIs

### PR DESCRIPTION
**Pull request by teddy-f-47**
Notably, the edit survey still has a bug because it creates a new survey instead of editing the existing one. But whatever.

### CODE REVIEW

**Comment by artikandri** [comment]
🤣🤣🤣

Thank you for the hard work. Since we will have exam and we have to study, I will just accept this PR without reviewing the code. Should I assist you with working on the README?

**Comment by teddy-f-47** [comment]
> 🤣🤣🤣
> 
> Thank you for the hard work. Since we will have exam and we have to study, I will just accept this PR without reviewing the code. Should I assist you with working on the README?

I am writing it right now, maybe tomorrow you can revise and modify it a bit. Thanks!

**Comment by artikandri** [comment]
Alright,  I will see to it. Feel free to ask if you have questions about
the functionalities of some folders/files, and I will be glad to help.

niedz., 19 cze 2022, 23:59 użytkownik Teddy Ferdinan <
***@***.***> napisał:

**Comment by teddy-f-47** [comment]
Hello, I have merged this PR and finished writing the readme. You can read the front-end section in the root readme file of branch dev. thanks~!

**Comment by artikandri** [comment]
Alright, I have read it and everything looks fine. Thank you so much for the hard work! Have a good rest.

**Pull request merged**
