### PR TITLE
feat: tests on surveys page, settings page

### PR DESCRIPTION
**Pull request by artikandri**
### What's new: 
- ui/src/mocks/server/api.js : mockApis to be imported in ui/src/mocks/server/index.js
- ui/src/mocks/server/index.js: mocks the server. Only called when IS_API_MOCKED is set to `true`
- ui/src/util/numbers.js: new number utils
 ui/tests/e2e/specs/user/surveys/*: surveys test cases; written by following https://docs.google.com/spreadsheets/d/1520cPiCYmGez-RDz2H5gv_CBpS1AW_hZcQylUM9_0so/edit#gid=1852052762

### What's changed: 
- ui/.env.* : added a new variable called IS_API_MOCKED to specify api mocking. Restart node to apply the changes. 
- ui/cypress.config.js: added IS_API_MOCKED  variable. 
-  ui/package.json: added a new package (miragejs) to create mock server when IS_API_MOCKED returns true and NODE_ENV is in development mode
- ui/src/api/index.js: exported the urls to another file, so that it can be reused in cypress. Also set the headers in config file instead 
- ui/src/main.js: imported the makeServer function
- ui/src/views/user/survey-detail/SurveyDetailView.vue: minor styling
- ui/src/views/user/survey-detail/* : added some classes to make testing easier
- ui/src/views/user/surveys/SurveysView.vue: added some classes to make testing easier
- ui/src/views/user/surveys/*:: added some classes to make testing easier
- ui/tests/e2e/specs/user/login/login.cy.js: refactored.
- ui/tests/e2e/specs/user/settings/settings.cy.js: refactored, added some more scenarios
- ui/tests/e2e/specs/user/signup/signup.cy.js: refactored
- ui/tests/e2e/support/commands.js: refactored, new commands for easier testing
- ui/tests/e2e/support/api/index.js: refactored; imported urls from "@/api/urls" instead of hard-coding the second time to ensure consistency 
- ui/vue.config.js : added IS_API_MOCKED variable

### Notable: 
- In case of unreliable BE connection, we can use Mirage.js to mock the API instead. However, Mirage has limitation with Cypress; it cannot work with cy.request and cy.interceptor. cy.request will not accept responses mocked by Mirage, and cy.interceptor will not intercept the request sent to Mirage. 
- user/confirm page (or basically any get apis that gives no id/params/whatsoever in the url)  cannot be tested in mock mode. This is because the user/notactivated url has the GET method, and it has no params to differ successful and unsuccessful response. I can mock POST apis by changing the value (ex: mocking the email), but with GET apis its impossible because cy.interceptor doesnt work with Mirage.js

### To do: 
- Finding out how to implement process.env variables with cypress (low priority) 
- validation in survey edit page
- More tests? My part is already done tho, but in case someone else need help XD   tho I cannot help much
- fixing routing bugs. Now sometime the navigation guard will catch error on route changes
- Helping api implementation in survey edit page (can only mock tho, I gave up with docker already) 

### Screenshots:  
snapshot_user_surveys_delete
snapshot_user_surveys_edit
snapshot_user_surveys_surveys
snapshot_user_surveys_tnc
snapshot_user_settings
snapshot_user_signup
snapshot_user_surveys_create

cc @Daedheldir. This PR contains useful references for the tests, please check.

### CODE REVIEW

**Comment by teddy-f-47** [comment]
Thank you for your hard work! I think this looks ok. However in my opinion, we should merge #47 and #49 first, and after that this PR can be merged.

**Comment by artikandri** [comment]
> Thank you for your hard work! I think this looks ok. However in my opinion, we should merge #47 and #49 first, and after that this PR can be merged.

Sure XD Please check my suggestions and inform me later.

**Comment by artikandri** [comment]
> Thank you for your hard work! I think this looks ok. However in my opinion, we should merge #47 and #49 first, and after that this PR can be merged.

Hello, I have resolved the conflicts, please check and dont forget to approve if you have no comments/revision on the code :)

**Review by teddy-f-47 — COMMENTED** [review]
I think the code is ok, from implementation perspective the change is only we need to take out URLs from ui/api/index.js to its own file ui/src/api/urls.js.

Please rebase and resolve conflicting files, and after that I think it can be merged just fine. Do you want me to do the rebase and resolve conflicts?

**Comment by teddy-f-47** [comment]
oh so you have resolved the conflicts XD ok, I will check once more

**Review by teddy-f-47 — APPROVED** [review]
Ok, once again thank you for your hard work! Approved for merging.

**Comment by artikandri** [comment]
> I think the code is ok, from implementation perspective the change is only we need to take out URLs from ui/api/index.js to its own file ui/src/api/urls.js.
> 
> Please rebase and resolve conflicting files, and after that I think it can be merged just fine. Do you want me to do the rebase and resolve conflicts?

I have moved them to urls file as well,  please check :)

**Pull request merged**
