### PR TITLE
feat: finished survey fill view page

### PR DESCRIPTION
**Pull request by artikandri**
### What's new: 
- ui/src/assets/json/survey-data-sample.json: json file sample of a survey data generated in the front end side. 

### What's changed:
- ui/.eslintrc.js: added global variables to be ignored by eslint (_, moment)
- ui/src/components/ContentCard.vue: refactored; made the component more general by adding some props to customize the callback and the button text 
- ui/src/views/general/survey-fill/SurveyFillView.vue: worked on the survey page for the respondents
- ui/src/views/user/signup-thankyou/SignupThankyouView.vue: minor styling

The rest of the changes were caused by `yarn lint --fix`

#### Mobile: 

image
image
image
image

#### Desktop: 
image
image
image
image

### To do : 
- survey detail page
- implementing the api. Somehow I'm always encountering "Internal server error" when I'm trying to access the API. The problem persists even though I have removed my docker image and rebuild it several times, so I'm still investigating the problem.

### CODE REVIEW

**Review by teddy-f-47 — APPROVED** [review]
Thank you for the work. Approved. However, keep in mind that we probably will not implement all those 'downloadable' requirements such as the button for the responder to download their response as a PDF file. For now, we can keep it, we will just see in the future if we will have to remove the "download PDF" button and the other share buttons.

I am also investigating the same internal server error with the API calls. I think I have found the nginx configuration that allows API calls from a different port, but now I get error 500 as well when making API requests. I think we need to somehow manually structure the API request to suit the example, and it seems the data should be placed in 'body' - 'raw' fields, but I haven't tested it yet.

**Comment by artikandri** [comment]
Yeah, I know the feature will likely be removed, but I like working on them XD so I did. 

Have you checked the errors in your docker cmd? In mine it shows up that the api container cannot connect to the db container somehow; and no idea why.  Now I'm dropping it since I think the survey detail page needs my attention more, but I will get back to it tomorrow. 

Will be merged.

**Comment by teddy-f-47** [comment]
> Yeah, I know the feature will likely be removed, but I like working on them XD so I did.
> 
> Have you checked the errors in your docker cmd? In mine it shows up that the api container cannot connect to the db container somehow; and no idea why. Now I'm dropping it since I think the survey detail page needs my attention more, but I will get back to it tomorrow.
> 
> Will be merged.

In my case, it seems that the db container connects just fine.... db_1 ready for connections

I just tested using a manually structured API request, and I don't get error 500 anymore... instead I get: "API Response Error: TypeError: t.replace is not a function"

Screenshot of API Response Error:
0API_response_error

My nginx.conf file:
1nginx_conf

My ui/src/api/index.js file:
2api_indexjs

My SignupView.vue file:
3signup_view

**Comment by artikandri** [comment]
Now this gets more interesting  XD i think its because you specified your first argument as object instead of the url string.  Have you tried axios.post("url", {})? {} stands for your config

**Comment by artikandri** [comment]
So since its working on ur side, most probably the problem lies with the axios settings and my env. Can u fix it? I think the problem has to do with the json data needs to be stringified before sending, also some other settings.

**Comment by artikandri** [comment]
I can work on axios settings once I got my env fixed but until now I have no idea how :"  I want to drop the whole container and images but thats my last resort.. but if I still cant get it working tomorrow then I probably will XD

**Comment by teddy-f-47** [comment]
I still need more time to investigate this. I just tried the original axios code (the one with simply `return axios.post(USER_SIGNUP_URL, data);`) to observe the logs in the cmd, and this is what i found. No db error, but the api container says that no python application found, which is really weird

```
nginx         | 172.18.0.1 - - [12/Jun/2022:19:29:20 +0000] "OPTIONS /api/authentication/signup HTTP/1.1" 204 0 "http://localhost:8001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "-"
api           | --- no python application found, check your startup logs for errors ---
api           | [pid: 13|app: -1|req: -1/1] 172.18.0.1 () {58 vars in 1013 bytes} [Sun Jun 12 19:29:20 2022] POST /api/authentication/signup => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
nginx         | 172.18.0.1 - - [12/Jun/2022:19:29:20 +0000] "POST /api/authentication/signup HTTP/1.1" 500 32 "http://localhost:8001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "-"
```

I will inform you later if i make any progress. For now, I suspect that the problem is as you said, the json data needs to be stringified, and we need to structure the api request exactly like the example.

For fixing the env..... maybe you need to `docker-compose build --no-cache` followed by `docker-compose up` ? :<

**Comment by artikandri** [comment]
Yeah, thats also the error I found,  and if you scrolled up, you may also
find more errors.. XD or at least thats what happened to me. I want to
investigate more but again, I am still working on the survey detail page. I
will inform u later when I started working on api again.

Alternatively you can also try investigating by using fetch (there is an
example somewhere) instead of axios, just in case our problem did lie with
axios.

niedz., 12 cze 2022, 21:37 użytkownik Teddy Ferdinan <
***@***.***> napisał:

**Comment by teddy-f-47** [comment]
I have tried all sorts of ways of structuring the api request, but it either fails to be parsed by js, or it gets internal server error response 500. Here is my latest attempt using traditional fetch:

The code:
1error_with_fetch_post

The error found in browser:
0error_with_fetch_post

The error in cmd, same with no python app found:
2error_with_fetch_post

**Comment by artikandri** [comment]
Then I think we got the same errors XD  because those errors are also what
I got, whether

niedz., 12 cze 2022, 22:42 użytkownik Teddy Ferdinan <
***@***.***> napisał:

**Comment by teddy-f-47** [comment]
Hi, this is just to inform that I finally figured out how to make the API call correctly, we just need to stringify the data. Please forget about the nginx.conf modification I made above because it is not needed at all. Here's screenshot of the working code using traditional fetch (I will try using axios as well later):
yes1

**Pull request merged**
